name : create a comment on new issues

on:
    issues:
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "dump github contexte"
              run: echo '${{ toJson(github.event)}}' | jq
              shell: bash
            - name: Create Comment
              uses: peter-evans/cretae-or-update-comment@v1
              with:
                issue_number: ${{ github.event.issue.number }}
                body: |
                 This is a multi-line test comment
                 - With GitHub **MarkDown** : Sparkles:
                 - Created by [create-or-update-comment][1]

                 [1]: https://github.com/peter-evans/cretae-or-update-comment
                 
                reactions: '+1'
    comment-with-api:
        runs-on: ubuntu-latest
        steps:
            - name: Create a Comment with API
              run: |
                gh api -X POST \
                https://api.github.com/repo/${ORGANIZATION}/${REPOSITRY}/issues/${ISSUE_NUMBER}/comments \
                -f body='
                Comment but from the PI Call not action'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ORGANIZATION: ${{ github.event.organization.login }}
                REPOSITRY: ${{ github.event.repository.name}}
                ISSUE_NUMBER: ${{ github.event.issue.number}}
