name : create a comment on new issues

on:
    issues:
        types: [opened]

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "dump github contexte"
              run: echo '${{ toJson(github.event)}}' | jq
              shell: bash